[workspace]

members = [
  "benches",
  "circom-compat",
  "kzg",
  "ipa",
  "snark",
]

[patch.crates-io]
ark-ff = { path = "local_dep/algebra/ff"}
ark-ec = { path = "local_dep/algebra/ec" }
ark-serialize = { path = "local_dep/algebra/serialize" }
ark-bn254 = { path = "local_dep/curves/bn254" }
ark-bls12-381 = { path = "local_dep/curves/bls12_381" }
ark-relations = { path = "local_dep/snark/relations" }

[profile.release]
lto = "fat"
