[package]
name = "ark-simple-payments"
version = "0.4.0"
authors = [ "arkworks contributors" ]
description = "A simple payments system"
repository = "https://github.com/arkworks-rs/r1cs-tutorial"
keywords = ["cryptography", "relations", "r1cs"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
ark-ff = { version = "^0.4.0", default-features = false }
ark-ec = { version = "^0.4.0", default-features = false }
ark-std = { version = "^0.4.0", default-features = false }
ark-relations = { version = "^0.4.0", default-features = false, optional = true }
ark-serialize = { version = "^0.4.0", default-features = false, features = [ "derive" ] }

ark-r1cs-std = { version = "^0.4.0", optional = true, default-features = false }
ark-snark = { version = "^0.4.0", default-features = false }

ark-crypto-primitives = { version = "0.4.0" }
blake2 = { version = "0.10", default-features = true }
sha2 = { version = "0.10", default-features = false }
digest = { version = "0.10", default-features = false }
merlin = { version = "3.0.0", default-features = false, optional = true }

rayon = { version = "1.0", optional = true }
derivative = { version = "2.0", features = ["use_core"] }
tracing = { version = "0.1", default-features = false, features = [ "attributes" ], optional = true }
hashbrown = { version = "0.14", default-features = false, features = ["inline-more", "allocator-api2"], optional = true  }
ark-ed-on-bls12-381 = { version = "^0.4.0", default-features = false, features = [ "r1cs" ] }
ark-bls12-381 = { version = "^0.4.0" }
ark-ed-on-bn254 = { version = "0.4.0-alpha.2", default-features = false, features = [ "r1cs" ] }
ark-bn254 = { version = "0.4.0-alpha.2", features = [ "curve", "asm" ] }

[features]
default = [ "std", "parallel", "r1cs", "merkle_tree", "prf" ]
std = [ "ark-ff/std", "ark-ec/std", "ark-std/std", "ark-relations/std", "ark-serialize/std", "ark-crypto-primitives/std" ]
r1cs = [ "ark-relations", "ark-r1cs-std", "ark-crypto-primitives/r1cs" ]
parallel = [ "std", "ark-ff/parallel", "ark-ec/parallel", "ark-std/parallel" ]
merkle_tree = ["ark-crypto-primitives/crh", "ark-crypto-primitives/merkle_tree"]
prf = [ "ark-crypto-primitives/prf" ]

[dev-dependencies]
ark-ed-on-bls12-377 = { version = "^0.4.0", default-features = false }
ark-ed-on-bls12-381 = { version = "^0.4.0", default-features = false, features = [ "r1cs" ] }
ark-bls12-377 = { version = "^0.4.0", default-features = false, features = [ "curve", "r1cs" ] }
ark-mnt4-298 = { version = "^0.4.0", default-features = false, features = [ "curve", "r1cs" ] }
ark-mnt6-298 = { version = "^0.4.0", default-features = false, features = [ "r1cs" ] }
criterion = { version = "0.4" }